//! Renders the contract modules to TypeScript.
//!
//! Each module becomes one file under `crates/kchess-contracts/ts/generated/`. A module lists its items
//! (ts-rs declarations, raw declarations that ts-rs cannot express, and runtime `as const`
//! arrays); the renderer adds `import type` lines for the names other modules own, so a module
//! never names a type it does not import.

use std::collections::{BTreeMap, BTreeSet};

use serde_json::Value;
use ts_rs::{Config, TS};

/// One TypeScript declaration or runtime value in a generated module.
pub enum Item {
    /// A type ts-rs declares: `decl` is ts-rs output without the leading `export`.
    Decl { name: String, decl: String },
    /// A declaration written out as TypeScript (indexed access, `keyof`, generics, ...).
    Raw { name: String, text: String },
    /// `export const NAME = [ ... ] as const<suffix>;` built from wire values.
    Const {
        name: String,
        values: Vec<Value>,
        suffix: String,
    },
}

impl Item {
    /// The ts-rs declaration of `T`.
    pub fn of<T: TS + ?Sized>(cfg: &Config) -> Self {
        Item::Decl {
            name: T::ident(cfg),
            decl: T::decl(cfg),
        }
    }

    fn name(&self) -> &str {
        match self {
            Item::Decl { name, .. } | Item::Raw { name, .. } | Item::Const { name, .. } => name,
        }
    }

    fn text(&self) -> String {
        match self {
            Item::Decl { decl, .. } => format!("export {decl}"),
            Item::Raw { text, .. } => text.clone(),
            Item::Const {
                name,
                values,
                suffix,
            } => {
                let body = values
                    .iter()
                    .map(|v| serde_json::to_string(v).expect("const value serializes"))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("export const {name} = [{body}] as const{suffix};")
            }
        }
    }
}

/// A generated module: `generated/<stem>.ts`.
pub struct Module {
    pub stem: &'static str,
    pub items: Vec<Item>,
    /// Names this module passes on from another module, e.g. `Variant` from `variant`.
    pub reexports: Vec<(&'static str, Vec<&'static str>)>,
}

const HEADER: &str = "// Generated by crates/kchess-contracts (`cargo run -p kchess-contracts --bin export-types`).\n\
// Do not edit: change the Rust contract types and run `pnpm run build:native`.\n";

/// Renders every module to `(file name, contents)`, sorted by file name.
///
/// Panics on a contract error: two modules owning one name, or a declaration that names a type
/// no module declares. Both are bugs in the Rust contracts, caught by `--check` and the tests.
pub fn render(modules: &[Module]) -> BTreeMap<String, String> {
    let mut owner: BTreeMap<&str, &str> = BTreeMap::new();
    for module in modules {
        for item in &module.items {
            if let Some(previous) = owner.insert(item.name(), module.stem) {
                panic!(
                    "{} is declared in both {previous} and {}",
                    item.name(),
                    module.stem
                );
            }
        }
    }
    let mut files = BTreeMap::new();
    for module in modules {
        let own: BTreeSet<&str> = module.items.iter().map(Item::name).collect();
        let mut used: BTreeMap<&str, BTreeSet<String>> = BTreeMap::new();
        for item in &module.items {
            let text = item.text();
            for ident in identifiers(&strip_comments(&text)) {
                let ident = ident.as_str();
                if own.contains(ident) {
                    continue;
                }
                match owner.get(ident) {
                    Some(stem) => {
                        used.entry(stem).or_default().insert(ident.to_string());
                    }
                    None if is_builtin(ident)
                        || !ident.starts_with(|c: char| c.is_ascii_uppercase()) => {}
                    None => panic!(
                        "{} references {ident}, which no contract module declares",
                        module.stem
                    ),
                }
            }
        }

        let mut out = String::from(HEADER);
        for (stem, names) in &used {
            let list = names.iter().cloned().collect::<Vec<_>>().join(", ");
            out.push_str(&format!("\nimport type {{ {list} }} from './{stem}'"));
        }
        out.push('\n');
        for (stem, names) in &module.reexports {
            out.push_str(&format!(
                "\nexport type {{ {} }} from './{stem}'",
                names.join(", ")
            ));
        }
        for item in &module.items {
            out.push('\n');
            out.push_str(&item.text());
            out.push('\n');
        }
        files.insert(format!("{}.ts", module.stem), out);
    }
    files
}

/// TypeScript names that need no import.
fn is_builtin(ident: &str) -> bool {
    matches!(
        ident,
        // Generic parameters of raw declarations (`AppData<S>`, `saveSession<K>`).
        "S" | "K"
            | "Record"
            | "Partial"
            | "Omit"
            | "Exclude"
            | "Promise"
            | "Uint8Array"
            | "Array"
            | "String"
            | "Number"
            | "Boolean"
            | "BigInt"
            | "Date"
            | "Error"
            | "Readonly"
            | "Pick"
            | "Required"
            | "ReadonlyArray"
            | "Map"
            | "Set"
            | "PromiseLike"
            | "AbortSignal"
            | "Object"
            | "JSON"
            | "Math"
            | "Infinity"
            | "NaN"
    )
}

/// The text without `/* … */` comments (ts-rs writes doc comments as JSDoc blocks).
fn strip_comments(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(start) = rest.find("/*") {
        out.push_str(&rest[..start]);
        match rest[start..].find("*/") {
            Some(end) => rest = &rest[start + end + 2..],
            None => {
                rest = "";
            }
        }
    }
    out.push_str(rest);
    out
}

/// Identifiers in TypeScript text, with string literals removed (their contents are data).
fn identifiers(text: &str) -> Vec<String> {
    let bytes = text.as_bytes();
    let mut out = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        let c = bytes[i];
        if c == b'\'' || c == b'"' {
            // Skip the literal; a backslash escapes the next byte.
            i += 1;
            while i < bytes.len() && bytes[i] != c {
                if bytes[i] == b'\\' {
                    i += 1;
                }
                i += 1;
            }
            i += 1;
        } else if c.is_ascii_alphabetic() || c == b'_' {
            let start = i;
            while i < bytes.len() && (bytes[i].is_ascii_alphanumeric() || bytes[i] == b'_') {
                i += 1;
            }
            // Only capitalised names can be contract types or values; lower-case words are
            // keywords, primitives or property names. A name followed by `:` or `?:` is a key.
            let mut next = i;
            while next < bytes.len() && bytes[next] == b' ' {
                next += 1;
            }
            let is_key = next < bytes.len()
                && (bytes[next] == b':'
                    || (bytes[next] == b'?' && bytes.get(next + 1) == Some(&b':')));
            if !is_key {
                out.push(text[start..i].to_string());
            }
        } else {
            i += 1;
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identifiers_skip_string_literals() {
        let names = identifiers("export type A = { \"Foo\": B; c: 'Bar' | C }");
        assert!(names.iter().any(|n| n == "B"));
        assert!(names.iter().any(|n| n == "C"));
        assert!(!names.iter().any(|n| n == "Foo"));
        assert!(!names.iter().any(|n| n == "Bar"));
    }

    #[test]
    fn cross_module_references_are_imported() {
        let modules = vec![
            Module {
                stem: "a",
                items: vec![Item::Raw {
                    name: "A".into(),
                    text: "export type A = number;".into(),
                }],
                reexports: vec![],
            },
            Module {
                stem: "b",
                items: vec![Item::Raw {
                    name: "B".into(),
                    text: "export type B = A[];".into(),
                }],
                reexports: vec![("a", vec!["A"])],
            },
        ];
        let files = render(&modules);
        let b = &files["b.ts"];
        assert!(b.contains("import type { A } from './a'"), "{b}");
        assert!(b.contains("export type { A } from './a'"), "{b}");
    }

    #[test]
    #[should_panic(expected = "references Missing")]
    fn unknown_references_fail() {
        let modules = vec![Module {
            stem: "a",
            items: vec![Item::Raw {
                name: "A".into(),
                text: "export type A = Missing;".into(),
            }],
            reexports: vec![],
        }];
        render(&modules);
    }
}
