[workspace]
members = [".", "crates/kchess_board", "crates/kchess_board_api"]
resolver = "2"

[package]
name = "kchess"
version = "0.1.0"
edition = "2024"
default-run = "KChess"

[[bin]]
name = "KChess"
path = "src/main.rs"

[dependencies]
gpui = { version = "0.2.2", features = ["runtime_shaders"] }
kchess_board = { path = "crates/kchess_board", features = ["gpui"] }
kchess_board_api = { path = "crates/kchess_board_api" }
unicode-segmentation = "1.11"
