import { DEFAULT_ENGINE_LEVELS } from './engineLevels.ts'
import type { Settings } from './types'

export const DEFAULT_SETTINGS: Settings = {
  appearance: 'system',
  boardTheme: 'brown',
  lightTheme: 'kchess',
  darkTheme: 'kchess',
  pieceSet: 'cburnett',
  pieceAnimation: 'normal',
  coordinates: 'inside',
  soundEnabled: true,
  soundVolume: 0.7,
  enginePath: '',
  premove: true,
  promotion: 'ask',
  showLegalMoves: true,
  notificationsEnabled: true,
  notifyActive: false,
  notifyBackground: true,
  notifyOpponentMove: true,
  notifyLowTime: true,
  notifyGameEvents: true,
  notifyComputerMove: true,
  notifySound: false,
  voicePushToTalk: false,
  voiceConfirmMoves: true,
  voiceHistory: true,
  updateAutoCheck: true,
  updateAutoDownload: true,
  updateInstallOnQuit: true,
  engineLevels: [...DEFAULT_ENGINE_LEVELS],
  reviewAuto: 'recent',
  reviewOnBattery: false,
  receiveChallenges: true,
  notifyChallenges: true,
  onlineChat: true,
  correspondencePoll: 5,
  zenMode: false,
  blindfold: false,
  cloudEval: false,
  showOpeningName: true,
}
